### ISSUE TITLE
Follow-up on #183

### ISSUE THREAD

**Issue by skearnes** [open-reaction-database/ord-data#193]
> @skearnes thanks for the clarification. I thought it would be that. We will hold on that for now though. Me and @qai222 had a discussion at OH today, and there may be some changes we want to make to the dataset before pushing it to main.

I uploaded my processing scripts to [this repo](https://github.com/qai222/ord_submission/blob/master/dataset_47463309/process.py). A few notes from the discussion with @bdeadman and the script:
1. The `solvent.volume` should have `volume_includes_solutes=True` specified. This field is unspecififed in the current submission. 
2. Convention needed for describing room temperature as a `Temperature` message.
3. Convention needed for describing pre-mix, e.g. 
   ```
   After placing the 96-well plates in ultrasonic water bath for 10 seconds to mix the reaction uniformly, 
   each 96-well plate was covered with an optical glass to minimize the volatilization of solvent and component
   ```
   (right now this is in `ReactionSetup.environment`).
4. The quantification of products includes a derivatization reaction. One can include it as `ReactionWorkups` or referencing another `Reaction` record. We chose the former. This led to ambiguity in assigning `reaction_role`: A is added as a catalyst of the derivatization reaction, should the role of A be `workup` or `catalyst`?
5. `ReactionInput` has `addition_order` specified, but `workups` is a sequence, so `workup1` precedes `workup2` implies `workup1.input.addition_order >= workup2.input.addition_order`. There should be a validation function for this.
6. Enantiomer products: what should the product SMILES be in reaction SMILES (one without chiral or two with chiral)? how should one describe the `ProductCompound`? What I did is
   ```
   ProductCompound(
    identifiers=[
        CompoundIdentifier(type="SMILES", value=product_s_smi),
        CompoundIdentifier(type="SMILES", value=product_r_smi),
    ],
    is_desired_product=True,
   ...
   ```

_Originally posted by @qai222 in https://github.com/open-reaction-database/ord-data/issues/183#issuecomment-2211543575_

**Comment by bdeadman** [comment]
[data-1721320121427.csv](https://github.com/user-attachments/files/16286336/data-1721320121427.csv)
 
This list of 27 reactions is everything in the ORD with an 'EE' selectivity type. I searched for 'ER' as well but the query returned no hits.

**Comment by qai222** [comment]
> [data-1721320121427.csv](https://github.com/user-attachments/files/16286336/data-1721320121427.csv)
> 
> This list of 27 reactions is everything in the ORD with an 'EE' selectivity type. I searched for 'ER' as well but the query returned no hits.

Looks like all of them just have one configuration as the product... I guess it might be OK when it is obvious there is only another configuration. I think we can create a convention so the structures of all configurations are included.

**Comment by bdeadman** [comment]
Possible styles for reporting chiral products:

Option A - Major enantiomer only with an enantioselectivity measurement associated with the single enantiomer product. The product description only has the major enantiomer.

[example 1](https://open-reaction-database.org/id/ord-e5c44ec1b5164f8ea077cf3b7ee0214a
)
![image](https://github.com/user-attachments/assets/8f3f1bad-9eaa-4fd8-bc72-6180b404a0ad)

[example 2](https://open-reaction-database.org/id/ord-76ac76ddff4041c5b4e05ca3d58f7db5)
![image](https://github.com/user-attachments/assets/a25ce31b-0af2-415b-8b43-581f09c49128)

[example 3](https://open-reaction-database.org/id/ord-d6b9dd0540384aabb43de1a705566c05
)
![image](https://github.com/user-attachments/assets/b0cb4a7f-dbfa-443c-a028-29542228891e)


Option B - Both enantiomers as separate products. Measurements of individual enantiomers (e.g. chiral peak area) associated with a single product. Selectivity defined at the outcome analysis level (rather than product measurement), with ee also recorded as a product measurement of the major enantiomer (but not the alternative enantiomer).
      
[enantioselective reaction option B example.pbtxt.gz](https://github.com/user-attachments/files/16361086/enantioselective.reaction.option.B.example.pbtxt.gz) This is an example from a dataset being prepared by @bdeadman based on [https://doi.org/10.1021/acscatal.3c02859](https://doi.org/10.1021/acscatal.3c02859).

**Comment by bdeadman** [comment]
Both options have their merits. Option A is consistent with how such reactions are typically reported in the literature. This is also how the 27 existing chiral reactions in the ORD have been recorded. 

In option B the alternative enantiomer is explicit instead of implied. This option also works well if there is measurement data of the individual enantiomer (e.g. chiral peak area) instead of just ratio/excess. For simple product mixtures the enanitoselectivity reported at outcome measurement level is unambiguous, but if the product mixture is complex (contains more than just the enantiomeric pair) then this could be ambiguous.

If I recall correctly, option B is similar to how the [Organic Reactions](https://onlinelibrary.wiley.com/doi/book/10.1002/0471264180) text book reports enantioselective reactions. They also prefer to use enantiomeric ratio over enantiomeric excess.

**Comment by bdeadman** [comment]
> > [data-1721320121427.csv](https://github.com/user-attachments/files/16286336/data-1721320121427.csv)
> > This list of 27 reactions is everything in the ORD with an 'EE' selectivity type. I searched for 'ER' as well but the query returned no hits.
> 
> Looks like all of them just have one configuration as the product... I guess it might be OK when it is obvious there is only another configuration. I think we can create a convention so the structures of all configurations are included.

Agreed but I will discuss it at office hour tonight.

**Comment by bdeadman** [comment]
**Room Temperature Convention**
[ambient temperatures.xlsx](https://github.com/user-attachments/files/16362617/ambient.temperatures.xlsx)

Best practice is for the experimenter to report their local room temperature with a precision value to indicate the likely range experienced by the reaction. For example this[ dataset from Novartis](https://open-reaction-database.org/search?dataset_id=ord_dataset-10b940e7982c4622b1e1ac879394aba6&limit=100) which was probably air conditioned.

In situations where the local room temperature is not known (e.g. data from a paper) then an estimate is needed. The USPTO dataset does not appear to have a consistent way of representing ambient temperature. 

My suggestion is to treat an unreported room temperature as 25 +- 5 or 10 degrees Celcius to cover the likely range. Alternatively the precision could be artificially high (e.g. 99) to indicate the value is assumed. I would also add the temperature control type as AMBIENT, and include a details field stating "room temperature value is assumed to be 25 C".

Example message for ambiguous room temperature:

conditions {
  temperature {
    control {
      type: AMBIENT
      details: "room temperature value is assumed to be 25 C"
    }
    setpoint {
      value: 25.0
      precision: 99.0
      units: CELSIUS
    }
  }
}

**Comment by bdeadman** [comment]
**Reporting the pre-mix**
I would include it as a CUSTOM stirring condition

conditions {
  stirring {
      type: CUSTOM
      details: "After placing the 96-well plates in ultrasonic water bath for 10 seconds to mix the reaction uniformly, 
each 96-well plate was covered with an optical glass to minimize the volatilization of solvent and component ..."
    }

**Reporting the atmosphere**
I suggest moving the vessel purge step from the vessel preparation to conditions.

conditions {
  pressure {
    control {
      type: AMBIENT
      details: "A transparent acrylic top layer was fixed to the container with 12 flange bolts, then the container was degassed with an oil pump for three times and refilled with nitrogen and the container was connected with a nitrogen balloon to ensure a nitrogen atmosphere for the reaction.\""
    }
    setpoint {
      value: 1.0
      units: ATMOSPHERE
    }
    atmosphere {
      type: NITROGEN
    }

**Comment by bdeadman** [comment]
**Reporting of the Derivitization Results**
Summarising the discussions we have had  with Connor:
- The reported product should be the intended product, rather than the derivitisation product.
- Derivitisation reaction is neither a workup or a separate reaction.
- Derivitisation reported in the analysis method details to make it clear the measurement is based on an X deriviative with SMILES Y.

**Comment by bdeadman** [comment]
**Workup Order** added as a feature request open-reaction-database/ord-schema#743

**Reporting enantiomeric products in product SMILES**
I suggest including the main enantiomer only and/or reporting them as two separate structures. In hindsight I think including both enantiomer smiles in a single product creates ambiguity about which one it is.

**Comment by bdeadman** [comment]
> My suggestion is to treat an unreported room temperature as 25 +- 5 or 10 degrees Celcius to cover the likely range.

From discussion with @connorcoley, @skearnes  and @qai222 on 24th July 2024, we have agreed to use 22 +- 5 deg Celcius for reporting ambiguous room temperature where local knowledge is not available.

**Comment by bdeadman** [comment]
> Reporting of the Derivitization Results

From above meeting we also determined that reactions with product characterisation by derivative can be reported as:

- Derivative product with measurements that are specific to that compound (e.g. LC peak area, weight etc), AND ALSO
- Desired product with the measurements after processing (e.g. yield).
